# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892

# 允许局域网的连接
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info
# Clash 的 RESTful API
external-controller: '0.0.0.0:9090'

# RESTful API 的口令
secret: ''

proxies:
  - name: "ssr-vultr"
    type: ssr
    server: vultr.donkeyroll.com
    port: 15111
    cipher: aes-256-cfb
    password: "Password124578zxcvb"
    obfs: tls1.2_ticket_auth
    protocol: origin
    obfs-param: ab89b222868.microsoft.com
    #     # protocol-param: "#"
    #         # udp: true
