version: '3.2'
services:
  clash:
    image: dreamacro/clash
    container_name: clash
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    restart: unless-stopped
    network_mode: "host"
    logging: &logging
      driver: json-file
      options: # log rotation
        max-size: "10m"
        max-file: "20"