version: '3.2'
services:
  clash:
    image: dreamacro/clash
    container_name: clash
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    restart: unless-stopped
    ports:
      - 7890:7890
      - 7891:7891
      - 7892:7892
      - 9090:9090
    logging: &logging
      driver: json-file
      options: # log rotation
        max-size: "10m"
        max-file: "20"