version: '3.2'
services:
  dnsmasq:
    image: haproxy:1.8-alpine
    container_name: haproxy
    restart: always
    ports:
      - 53:53/udp
      - 8080:8080
    volumes:
      - /etc/haproxy:/usr/local/etc/haproxy:ro
    logging: &logging
      driver: json-file
      options: # log rotation
        max-size: "10m"
        max-file: "20"